# Generated by Django 5.0 on 2026-05-07 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('cor_badge', models.CharField(default='#e63946', help_text='Cor em hexadecimal para o badge da categoria', max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to='autores/')),
                ('site', models.URLField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('resumo', models.TextField(help_text='Breve resumo para aparecer nos cards', max_length=500)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='artigos/')),
                ('imagem_credito', models.CharField(blank=True, help_text='Crédito da imagem', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=15)),
                ('destaque', models.BooleanField(default=False, help_text='Marcar para aparecer no destaque da homepage')),
                ('visualizacoes', models.PositiveIntegerField(default=0, editable=False)),
                ('tempo_leitura', models.PositiveIntegerField(default=0, editable=False, help_text='Tempo estimado em minutos')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='news.author')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='news.categoria')),
            ],
            options={
                'verbose_name_plural': 'Artigos',
                'ordering': ['-data_publicacao', '-criado_em'],
            },
        ),
    ]
