# Generated by Django 5.0 on 2026-05-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaDinamica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('sobre', 'Sobre Nós'), ('links', 'Links Rápidos'), ('termos', 'Termos de Uso'), ('privacidade', 'Privacidade'), ('contato', 'Contato')], max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField(help_text='HTML permitido')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página Dinâmica',
                'verbose_name_plural': 'Páginas Dinâmicas',
            },
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('url', models.URLField(help_text='Link para a rede social')),
                ('icone', models.CharField(help_text='Classe do ícone (ex: fab fa-facebook, fab fa-instagram, fab fa-twitter)', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
                'ordering': ['ordem'],
            },
        ),
    ]
